import { Zone, SensorNode, Alert, IrrigationSchedule, IrrigationLog, MoisturePoint } from "./types";

export const MOCK_ZONES: Zone[] = [
  {
    id: "zone-a",
    farmId: "farm-rg-01",
    name: "Zone A • North Grove",
    cropType: "Chemlali Olive Trees (180 trees)",
    moisture: 54,
    targetMoisture: 50,
    nitrogen: 220,
    phosphorus: 55,
    potassium: 185,
    lastWatered: "Today, 05:30 AM",
    status: "ok",
    nodeCount: 3,
    activeNodeCount: 3,
    areaHectares: 2.4,
    soilType: "Sandy Loam",
  },
  {
    id: "zone-b",
    farmId: "farm-rg-01",
    name: "Zone B • South Slope",
    cropType: "Chemlali Olive Trees (140 trees)",
    moisture: 33,
    targetMoisture: 45,
    nitrogen: 175,
    phosphorus: 24, // low (<30 ppm)
    potassium: 145,
    lastWatered: "Yesterday, 06:00 PM",
    status: "warning",
    nodeCount: 2,
    activeNodeCount: 2,
    areaHectares: 1.8,
    soilType: "Clay Loam",
  },
  {
    id: "zone-c",
    farmId: "farm-rg-01",
    name: "Zone C • Terraced Basin",
    cropType: "Sayali Olive Trees (95 trees)",
    moisture: null, // 0 active nodes -> disconnected state
    targetMoisture: 45,
    nitrogen: 140,
    phosphorus: 42,
    potassium: 120,
    lastWatered: "3 days ago, 05:00 AM",
    status: "critical",
    nodeCount: 1,
    activeNodeCount: 0,
    areaHectares: 1.2,
    soilType: "Rocky Calcareous",
  },
];

export const MOCK_NODES: SensorNode[] = [
  {
    id: "SN-RG-01",
    zoneId: "zone-a",
    zoneName: "Zone A • North Grove",
    farmId: "farm-rg-01",
    name: "Node 01 — North Ridge",
    battery: 94,
    rssi: -58,
    lastSeen: "1m ago",
    commMethod: "wifi",
    status: "online",
    x: 28,
    y: 26,
    moisture: 55,
    soilTemp: 23.4,
    ambientTemp: 28.7,
    humidity: 48,
  },
  {
    id: "SN-RG-02",
    zoneId: "zone-a",
    zoneName: "Zone A • North Grove",
    farmId: "farm-rg-01",
    name: "Node 02 — Central Well",
    battery: 88,
    rssi: -64,
    lastSeen: "3m ago",
    commMethod: "wifi",
    status: "online",
    x: 44,
    y: 34,
    moisture: 53,
    soilTemp: 24.1,
    ambientTemp: 29.2,
    humidity: 46,
  },
  {
    id: "SN-RG-03",
    zoneId: "zone-a",
    zoneName: "Zone A • North Grove",
    farmId: "farm-rg-01",
    name: "Node 03 — East Perimeter",
    battery: 72,
    rssi: -71,
    lastSeen: "4m ago",
    commMethod: "wifi",
    status: "online",
    x: 62,
    y: 24,
    moisture: 54,
    soilTemp: 23.9,
    ambientTemp: 28.5,
    humidity: 50,
  },
  {
    id: "SN-RG-04",
    zoneId: "zone-b",
    zoneName: "Zone B • South Slope",
    farmId: "farm-rg-01",
    name: "Node 04 — South Gully",
    battery: 42,
    rssi: -79,
    lastSeen: "14m ago",
    commMethod: "wifi",
    status: "warning",
    x: 36,
    y: 72,
    moisture: 32,
    soilTemp: 26.5,
    ambientTemp: 31.8,
    humidity: 38,
  },
  {
    id: "SN-RG-05",
    zoneId: "zone-b",
    zoneName: "Zone B • South Slope",
    farmId: "farm-rg-01",
    name: "Node 05 — Lower Drip Line",
    battery: 82,
    rssi: -66,
    lastSeen: "2m ago",
    commMethod: "wifi",
    status: "online",
    x: 64,
    y: 68,
    moisture: 34,
    soilTemp: 25.8,
    ambientTemp: 31.1,
    humidity: 40,
  },
  {
    id: "SN-RG-06",
    zoneId: "zone-c",
    zoneName: "Zone C • Terraced Basin",
    farmId: "farm-rg-01",
    name: "Node 06 — Terraced Outpost",
    battery: 11,
    rssi: -93,
    lastSeen: "4h 12m ago",
    commMethod: "wifi",
    status: "offline",
    x: 82,
    y: 48,
    moisture: null,
    soilTemp: 27.2,
    ambientTemp: 33.0,
    humidity: 32,
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alt-01",
    nodeId: "SN-RG-06",
    zoneName: "Zone C • Terraced Basin",
    type: "Node Offline",
    severity: "critical",
    message: "Telemetry heartbeat missing for >4 hours. Last reported battery at 11%.",
    value: "-93 dBm / 11%",
    triggeredAt: "24 min ago",
    acknowledged: false,
  },
  {
    id: "alt-02",
    zoneName: "Zone B • South Slope",
    type: "Soil Moisture Deficit",
    severity: "critical",
    message: "Zone B moisture dropped to 33% (threshold: 45%). Olive stress threshold imminent.",
    value: "33%",
    triggeredAt: "58 min ago",
    acknowledged: false,
  },
  {
    id: "alt-03",
    nodeId: "SN-RG-04",
    zoneName: "Zone B • South Slope",
    type: "Low Battery & Weak RSSI",
    severity: "warning",
    message: "Node battery down to 42% and signal attenuated to -79 dBm in southern gully.",
    value: "42% / -79 dBm",
    triggeredAt: "2 hours ago",
    acknowledged: false,
  },
  {
    id: "alt-04",
    zoneName: "Zone B • South Slope",
    type: "Nutrient Imbalance",
    severity: "warning",
    message: "Phosphorus level detected at 24 ppm, below target optimal range (30-80 ppm).",
    value: "24 ppm",
    triggeredAt: "3 hours ago",
    acknowledged: false,
  },
  {
    id: "alt-05",
    zoneName: "Zone A • North Grove",
    type: "Irrigation Completed",
    severity: "info",
    message: "Morning scheduled drip cycle finished successfully. Delivered 720 L of water.",
    value: "720 L",
    triggeredAt: "5 hours ago",
    acknowledged: true,
  },
  {
    id: "alt-06",
    zoneName: "All Zones",
    type: "Gateway Sync Check",
    severity: "info",
    message: "Daily cloud synchronization verified across local MQTT broker & base station.",
    value: "MQTT 200 OK",
    triggeredAt: "7 hours ago",
    acknowledged: true,
  },
  {
    id: "alt-07",
    nodeId: "SN-RG-06",
    zoneName: "Zone C • Terraced Basin",
    type: "Signal Packet Loss",
    severity: "warning",
    message: "Packet loss on terrace repeater exceeded 25% threshold before disconnect.",
    value: "28% Loss",
    triggeredAt: "Yesterday, 08:15 PM",
    acknowledged: true,
  },
];

export const MOCK_SCHEDULES: IrrigationSchedule[] = [
  {
    id: "sch-01",
    zoneId: "zone-a",
    zoneName: "Zone A • North Grove",
    scheduleType: "recurring",
    startTime: "05:30 AM",
    durationMinutes: 45,
    repeatDays: [1, 3, 5], // Mon, Wed, Fri
    moistureThreshold: 48,
    active: true,
    scheduledStart: null,
    scheduledEnd: null,
    firedAt: null,
  },
  {
    id: "sch-02",
    zoneId: "zone-b",
    zoneName: "Zone B • South Slope",
    scheduleType: "recurring",
    startTime: "06:00 PM",
    durationMinutes: 60,
    repeatDays: [2, 4, 6], // Tue, Thu, Sat
    moistureThreshold: 45,
    active: true,
    scheduledStart: null,
    scheduledEnd: null,
    firedAt: null,
  },
  {
    id: "sch-03",
    zoneId: "zone-c",
    zoneName: "Zone C • Terraced Basin",
    scheduleType: "recurring",
    startTime: "05:00 AM",
    durationMinutes: 50,
    repeatDays: [0, 3], // Sun, Wed
    moistureThreshold: 40,
    active: false,
    scheduledStart: null,
    scheduledEnd: null,
    firedAt: null,
  },
];

export const MOCK_IRRIGATION_LOGS: IrrigationLog[] = [
  {
    id: "log-01",
    zoneName: "Zone A • North Grove",
    startedAt: "Today, 05:30 AM",
    endedAt: "Today, 06:15 AM",
    skipped: false,
    waterUsedL: 720,
  },
  {
    id: "log-02",
    zoneName: "Zone B • South Slope",
    startedAt: "Yesterday, 06:00 PM",
    endedAt: "Yesterday, 07:00 PM",
    skipped: false,
    waterUsedL: 850,
  },
  {
    id: "log-03",
    zoneName: "Zone A • North Grove",
    startedAt: "2 days ago, 05:30 AM",
    endedAt: "2 days ago, 05:30 AM",
    skipped: true,
    skipReason: "Soil moisture (58%) exceeded threshold (48%) after heavy morning fog",
    waterUsedL: 0,
  },
  {
    id: "log-04",
    zoneName: "Zone C • Terraced Basin",
    startedAt: "3 days ago, 05:00 AM",
    endedAt: "3 days ago, 05:00 AM",
    skipped: true,
    skipReason: "Sensor Node SN-RG-06 offline — safety lockout prevented unmonitored cycle",
    waterUsedL: 0,
  },
  {
    id: "log-05",
    zoneName: "Zone B • South Slope",
    startedAt: "4 days ago, 06:00 PM",
    endedAt: "4 days ago, 07:00 PM",
    skipped: false,
    waterUsedL: 830,
  },
];

export const MOCK_MOISTURE_HISTORY: MoisturePoint[] = [
  { time: "00:00", zoneA: 52, zoneB: 38, zoneC: null },
  { time: "01:00", zoneA: 52, zoneB: 38, zoneC: null },
  { time: "02:00", zoneA: 51, zoneB: 37, zoneC: null },
  { time: "03:00", zoneA: 51, zoneB: 37, zoneC: null },
  { time: "04:00", zoneA: 50, zoneB: 36, zoneC: null },
  { time: "05:00", zoneA: 50, zoneB: 36, zoneC: null },
  { time: "06:00", zoneA: 62, zoneB: 35, zoneC: null }, // after 05:30 AM watering
  { time: "07:00", zoneA: 60, zoneB: 35, zoneC: null },
  { time: "08:00", zoneA: 58, zoneB: 35, zoneC: null },
  { time: "09:00", zoneA: 57, zoneB: 34, zoneC: null },
  { time: "10:00", zoneA: 56, zoneB: 34, zoneC: null },
  { time: "11:00", zoneA: 55, zoneB: 34, zoneC: null },
  { time: "12:00", zoneA: 55, zoneB: 33, zoneC: null },
  { time: "13:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "14:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "15:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "16:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "17:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "18:00", zoneA: 53, zoneB: 33, zoneC: null },
  { time: "19:00", zoneA: 53, zoneB: 33, zoneC: null },
  { time: "20:00", zoneA: 53, zoneB: 33, zoneC: null },
  { time: "21:00", zoneA: 53, zoneB: 33, zoneC: null },
  { time: "22:00", zoneA: 54, zoneB: 33, zoneC: null },
  { time: "23:00", zoneA: 54, zoneB: 33, zoneC: null },
];
